from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field


class WorkloadEntry(BaseModel):
    """SPIFFE Workload Registration Entry."""

    id: str = Field(..., description="Unique entry ID generated by SPIRE")
    spiffe_id: str = Field(..., description="Minted SPIFFE ID URI")
    parent_id: str = Field(..., description="Parent Agent or Node SPIFFE ID")
    selectors: List[str] = Field(default_factory=list, description="Attestation selectors")
    ttl: int = Field(default=3600, description="SVID Time-to-Live in seconds")
    admin: bool = Field(default=False, description="Whether workload possesses admin privileges")
    dns_names: List[str] = Field(default_factory=list, description="Associated DNS SAN names")
    created_at: Optional[str] = None
    expires_at: Optional[str] = None


class CreateEntryRequest(BaseModel):
    """Request payload for creating a new workload registration entry."""

    spiffe_id: str = Field(..., json_schema_extra={"example": "spiffe://demo.local/custom-worker"})
    parent_id: str = Field(
        default="spiffe://demo.local/node/agent",
        json_schema_extra={"example": "spiffe://demo.local/node/agent"},
    )
    selectors: List[str] = Field(
        ...,
        min_length=1,
        json_schema_extra={"example": ["docker:label:workload:custom-worker"]},
        description="One or more selector strings (e.g., docker:label:..., k8s:ns:..., unix:uid:...)",
    )
    ttl: int = Field(default=3600, ge=60, le=86400, description="SVID TTL in seconds")
    admin: bool = Field(default=False)
    dns_names: List[str] = Field(default_factory=list)


class CreateEntryResponse(BaseModel):
    """Response returned upon creating a workload entry."""

    status: str
    entry_id: str
    spiffe_id: str
    message: str


class NodeAgent(BaseModel):
    """Attested SPIRE Node Agent."""

    spiffe_id: str
    attested_at: Optional[str] = None
    expires_at: Optional[str] = None
    serial_number: Optional[str] = None
    status: str = "attested"
    selectors: List[str] = Field(default_factory=list)


class GenerateTokenRequest(BaseModel):
    """Request to mint an agent join token."""

    spiffe_id: str = Field(
        default="spiffe://demo.local/node/agent",
        json_schema_extra={"example": "spiffe://demo.local/node/agent"},
    )
    ttl: int = Field(default=600, ge=60, le=3600, description="Token TTL in seconds")


class GenerateTokenResponse(BaseModel):
    """Minted join token details."""

    token: str
    spiffe_id: str
    ttl: int
    docker_command: str


class TrustBundle(BaseModel):
    """SPIFFE Trust Domain Root Certificate Bundle."""

    trust_domain: str
    x509_authorities_count: int
    x509_authorities_pem: List[str]
    jwt_authorities_count: int


class OIDCDiscoveryDoc(BaseModel):
    """Standard OpenID Connect Discovery document."""

    issuer: str
    jwks_uri: str
    authorization_endpoint: Optional[str] = None
    response_types_supported: List[str] = Field(default_factory=list)
    id_token_signing_alg_values_supported: List[str] = Field(default_factory=list)


class JWKKey(BaseModel):
    """JSON Web Key (JWK)."""

    kty: str
    kid: str
    use: str
    alg: str
    n: Optional[str] = None
    e: Optional[str] = None


class JWKSResponse(BaseModel):
    """JWKS Public Keyset."""

    keys: List[Dict[str, Any]]


class HandshakeStep(BaseModel):
    """Step in the keyless mTLS handshake execution."""

    step_number: int
    title: str
    actor: str
    status: str
    details: str
    timestamp: str


class KeylessTestFlowRequest(BaseModel):
    """Request to execute a keyless test flow."""

    client_container: Optional[str] = "client-worker"
    target_url: Optional[str] = "https://backend-api:8443/api/secret-data"
    simulate_unauthorized: bool = False


class KeylessTestFlowResponse(BaseModel):
    """Result of keyless mTLS transaction test."""

    status: str
    message: str
    client_spiffe_id: str
    server_spiffe_id: str
    latency_ms: float
    status_code: int
    timestamp: str
    payload: Dict[str, Any] = Field(default_factory=dict)
    handshake_steps: List[HandshakeStep] = Field(default_factory=list)


class PolicyEvaluationRequest(BaseModel):
    """Policy evaluation check for a client SPIFFE ID."""

    client_spiffe_id: str
    required_spiffe_id: str = "spiffe://demo.local/client-worker"


class PolicyEvaluationResponse(BaseModel):
    """Decision output for policy evaluation."""

    allowed: bool
    decision_reason: str
    client_spiffe_id: str
    required_spiffe_id: str
    timestamp: str


class OverviewSummary(BaseModel):
    """High level overview and telemetry summary of the ZeroKey environment."""

    trust_domain: str
    spire_server_healthy: bool
    spire_agent_count: int
    workload_entries_count: int
    oidc_healthy: bool
    backend_api_healthy: bool
    active_svids: int
    system_version: str


class AuditLogEvent(BaseModel):
    """Audit log entry for workload identity events."""

    id: str
    timestamp: str
    event_type: str
    actor: str
    target: str
    status: str
    details: str
