log_level = "DEBUG"
domains = ["localhost", "spire-oidc", "127.0.0.1"]
insecure_addr = "0.0.0.0:8080"
listen_addr = "0.0.0.0:8080"

server_api {
    address = "unix:///run/spire/server-sockets/api.sock"
}
