FROM golang:1.24-alpine AS builder

WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download

COPY . ./
RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-w -s" -o /bin/client ./cmd/client

FROM alpine:3.19
RUN apk --no-cache add ca-certificates curl
WORKDIR /app
COPY --from=builder /bin/client /app/client

ENV SPIFFE_ENDPOINT_SOCKET="unix:///run/spire/sockets/agent.sock"
ENV SERVER_URL="https://backend-api:8443/api/secret-data"

CMD ["/app/client"]
