FROM golang:1.22-alpine AS builder

WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download

COPY . ./
RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-w -s" -o /bin/server ./cmd/server

FROM alpine:3.19
RUN apk --no-cache add ca-certificates curl
WORKDIR /app
COPY --from=builder /bin/server /app/server

ENV SPIFFE_ENDPOINT_SOCKET="unix:///run/spire/sockets/agent.sock"
EXPOSE 8443

CMD ["/app/server"]
